apiVersion: v1
kind: Service
metadata:
  name: jackal-1
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 58001
    targetPort: 58001
    nodePort: 58001
    protocol: TCP
    name: http
  - port: 58501
    targetPort: 58501
    nodePort: 58501
    protocol: TCP
    name: theia
  - port: 58601
    targetPort: 58601
    nodePort: 58601
    protocol: TCP
    name: webviz
  - port: 58701
    targetPort: 58701
    nodePort: 58701
    protocol: TCP
    name: rosbridge
  - port: 59001
    targetPort: 59001
    nodePort: 59001
    protocol: UDP
    name: webrtc
  selector:
    app: jackal-1	  
  selector:
    app: jackal-1	