apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-start
  namespace: robot-test-1
data:
  spot_start.sh: |
    #!/bin/bash
    sudo sed -i 's/9090/'"$ROSBRIDGE_PORT"'/g' /opt/ros/noetic/share/rosbridge_server/launch/rosbridge_websocket.launch	   
    source /opt/ros/noetic/setup.bash
    source ~/catkin_ws/devel/setup.bash
    export DISPLAY=:0          
    sleep 45s
    roscore &
    sleep 5s
    roslaunch spot_config gazebo.launch &
    sleep 5s
    roslaunch rosbridge_server rosbridge_websocket.launch &
    sleep 5s
    roslaunch spot_config navigate.launch &        
    sleep 5s
    echo "Session Running. Press [Return] to exit."
    read
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-supervisord
  namespace: robot-test-1
data:
  spot_supervisord.conf: |
    [program:spot]
    environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s"
    user=%(ENV_USER)s
    command=/etc/provedge/spot_start.sh
    autorestart=true
    priority=900
    stdout_logfile=/tmp/spot.log
    stdout_logfile_maxbytes=100MB
    stdout_logfile_backups=10
    redirect_stderr=true