apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-supervisord
data:
  spot_supervisord.conf: |
    [program:spot]
    environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s"
    user=%(ENV_USER)s
    command=/etc/provedge/spot_start.sh
    autorestart=true
    priority=900
    stdout_logfile=/tmp/spot.log
    stdout_logfile_maxbytes=100MB
    stdout_logfile_backups=10
    redirect_stderr=true