apiVersion: v1
kind: ConfigMap
metadata:
  name: jackal-supervisord
data:
  jackal_supervisord.conf: |
    [program:jackal]
    environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s"
    user=%(ENV_USER)s
    command=/etc/provedge/jackal_start.sh
    autorestart=true
    priority=900
    stdout_logfile=/tmp/jackal.log
    stdout_logfile_maxbytes=100MB
    stdout_logfile_backups=10
    redirect_stderr=true